app = "vision2doc"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  GEMINI_API_KEY = "AIzaSyB6W3nu_BS_uNKHPJuhQVgEKH8xtW0CBAI"
  NEXT_PUBLIC_GEMINI_API_KEY = "AIzaSyB6W3nu_BS_uNKHPJuhQVgEKH8xtW0CBAI"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "30s"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
